Fix cri-o patches
microsoft/azurelinux pull request #10460
Opened 2024-09-16 09:03 UTC by sindhu-karri

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [ ] The toolchain has been rebuilt successfully (or no changes were made to it)
- [ ] The toolchain/worker package manifests are up-to-date
- [ ] Any updated packages successfully build (or no packages were changed)
- [ ] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [ ] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [ ] All package sources are available
- [ ] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [ ] LICENSE-MAP files are up-to-date (`./LICENSES-AND-NOTICES/SPECS/data/licenses.json`, `./LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md`, `./LICENSES-AND-NOTICES/SPECS/LICENSE-EXCEPTIONS.PHOTON`)
- [ ] All source files have up-to-date hashes in the `*.signatures.json` files
- [ ] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [ ] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

What does the PR accomplish, why was it needed?

###### Change Log  

- Change
- Change
- Change

###### Does this affect the toolchain?  

**YES/NO**

###### Associated issues  

- #xxxx

###### Links to CVEs  
- https://nvd.nist.gov/vuln/detail/CVE-YYYY-XXXX

###### Test Methodology

- Pipeline build id: xxxx

2025-01-10 18:04 UTC, rikenm1 requested changes

2025-01-10 18:09 UTC, sindhu-karri commented on SPECS/cri-o/cri-o.spec
> -Patch15:        CVE-2022-32149.patch
Hi Riken, I removed two patches as they are causing the build to fail. Hence, I removed them in this PR. These CVEs would need to be addressed separately. 
The build failures were not found earlier because build was happening without the patch application earlier

2025-01-13 19:28 UTC, rikenm1 requested changes

2025-01-13 19:28 UTC, rikenm1 commented on SPECS/cri-o/cri-o.spec
> -Patch15:        CVE-2022-32149.patch
Sindhu, so the patch application was not happening?  I do see we already had autopatch in this spec before your changes though.

2025-01-20 06:41 UTC, sindhu-karri commented
Hi Riken, Yes, Patch application was not happening

2025-01-21 04:46 UTC, mfrw commented on SPECS/cri-o/cri-o.spec
> +%autopatch -p1
good catch

2025-01-22 18:02 UTC, rikenm1 commented
> Hi Riken, Yes, Patch application was not happening

Can you create a bug for unapplied patches? We probably do not want to leave the build to be broken or patches unapplied

2025-01-29 17:59 UTC, rikenm1 commented
this PR which was merged, already achieved what this PR is trying to do. 
https://github.com/microsoft/azurelinux/pull/11789 

@sindhu-karri , can you close this PR

2025-01-30 18:03 UTC, closed without merging