Lihl/dcos cli+kubernetes CVE
microsoft/azurelinux pull request #10606
Opened 2024-10-02 19:48 UTC by henryli001

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [ ] The toolchain has been rebuilt successfully (or no changes were made to it)
- [ ] The toolchain/worker package manifests are up-to-date
- [ ] Any updated packages successfully build (or no packages were changed)
- [ ] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [ ] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [ ] All package sources are available
- [ ] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [ ] LICENSE-MAP files are up-to-date (`./LICENSES-AND-NOTICES/SPECS/data/licenses.json`, `./LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md`, `./LICENSES-AND-NOTICES/SPECS/LICENSE-EXCEPTIONS.PHOTON`)
- [ ] All source files have up-to-date hashes in the `*.signatures.json` files
- [ ] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [ ] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

What does the PR accomplish, why was it needed?
- Add patch to resolve CVE-2024-28180 for dcos-cli and kubernetes on 2.0
- Add patch to resolve CVE-2024-24786 for kubernetes on 2.0

###### Change Log  

- Add patch to resolve CVE-2024-28180
- Add patch to resolve CVE-2024-28180 and CVE-2024-24786

###### Does this affect the toolchain?  

NO

###### Links to CVEs  
- https://nvd.nist.gov/vuln/detail/CVE-2024-28180
- https://nvd.nist.gov/vuln/detail/CVE-2024-24786

###### Test Methodology

- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=650637&view=results

2024-10-05 06:05 UTC, christopherco requested changes
Please separate changes into individual PRs for each change being made.

2024-10-07 23:48 UTC, jslobodzian approved these changes

2024-10-09 00:31 UTC, henryli001 commented
Have split up the PR into three sub-PRs:
dcos-cli CVE-2024-28180: https://github.com/microsoft/azurelinux/pull/10667
kubernetes CVE-2024-28180: https://github.com/microsoft/azurelinux/pull/10668
kubernetes CVE-2024-24786: https://github.com/microsoft/azurelinux/pull/10669

2025-04-11 18:22 UTC, Kanishk-Bansal commented
@henryli001 can you close this PR in favour of 
dcos-cli CVE-2024-28180: https://github.com/microsoft/azurelinux/pull/10667
kubernetes CVE-2024-28180: https://github.com/microsoft/azurelinux/pull/10668
kubernetes CVE-2024-24786: https://github.com/microsoft/azurelinux/pull/10669

2025-08-26 19:38 UTC, closed without merging