Upgrade nvidia-container-toolkit to fix CVE-2024-0132 CVE-2024-0133
microsoft/azurelinux pull request #10636
Opened 2024-10-06 04:24 UTC by mandeepsplaha

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [ ] The toolchain has been rebuilt successfully (or no changes were made to it)
- [ ] The toolchain/worker package manifests are up-to-date
- [ ] Any updated packages successfully build (or no packages were changed)
- [ ] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [ ] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [ ] All package sources are available
- [ ] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [ ] LICENSE-MAP files are up-to-date (`./LICENSES-AND-NOTICES/SPECS/data/licenses.json`, `./LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md`, `./LICENSES-AND-NOTICES/SPECS/LICENSE-EXCEPTIONS.PHOTON`)
- [ ] All source files have up-to-date hashes in the `*.signatures.json` files
- [ ] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [ ] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

What does the PR accomplish, why was it needed?

###### Change Log  

- Change
- Change
- Change

###### Does this affect the toolchain?  

**YES/NO**

###### Associated issues  

- #xxxx

###### Links to CVEs  
- https://nvd.nist.gov/vuln/detail/CVE-YYYY-XXXX

###### Test Methodology

- Pipeline build id: xxxx

2024-10-07 15:04 UTC, jslobodzian approved these changes

2024-10-07 16:57 UTC, henryli001 commented
Since you have upgraded nvidia-container-toolkit, you also need to upgrade the libnvidia-container package. The version of these two packages have to match or else the containerized GPU scenario will break.

2024-10-07 16:58 UTC, henryli001 requested changes
Since you have upgraded nvidia-container-toolkit, you also need to upgrade the libnvidia-container package. The version of these two packages have to match or else the containerized GPU scenario will break.

2024-10-07 19:39 UTC, PawelWMS commented
> Since you have upgraded nvidia-container-toolkit, you also need to upgrade the libnvidia-container package. The version of these two packages have to match or else the containerized GPU scenario will break.

@henryli001, since we're on the topic, do you know if there's are reason these two packages weren't added to the "Spec Entanglement Mismatch Check"? It sounds like it would help keeping these package in-sync.

2024-10-07 20:32 UTC, henryli001 commented
> > Since you have upgraded nvidia-container-toolkit, you also need to upgrade the libnvidia-container package. The version of these two packages have to match or else the containerized GPU scenario will break.
> 
> @henryli001, since we're on the topic, do you know if there's are reason these two packages weren't added to the "Spec Entanglement Mismatch Check"? It sounds like it would help keeping these package in-sync.

I'm not sure about the actual details of why these packages were not included but I think they should.

2024-10-08 02:20 UTC, mfrw commented on SPECS/libnvidia-container/libnvidia-container.spec
> +Version:        1.16.2
Fixes: https://github.com/microsoft/azurelinux/pull/10636

2024-10-08 17:51 UTC, henryli001 approved these changes

2024-10-08 18:23 UTC, anphel31 approved these changes

2024-10-08 18:36 UTC, merged