Patch vim to resolve CVE-2024-43802
microsoft/azurelinux pull request #10681
Opened 2024-10-09 23:08 UTC by sameluch

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./LICENSES-AND-NOTICES/SPECS/data/licenses.json`, `./LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md`, `./LICENSES-AND-NOTICES/SPECS/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [x] Ready to merge

---

###### Summary 

What does the PR accomplish, why was it needed?
Patch CVE-2024-43802 within the vim package on Azure Linux 3.0.

###### Change Log  

- Add patch for CVE-2024-43802

###### Does this affect the toolchain?  

**NO**

###### Links to CVEs  
- https://nvd.nist.gov/vuln/detail/CVE-2024-43802

###### Test Methodology

- Pipeline build id: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=654272&view=results

2024-10-10 23:55 UTC, christopherco requested changes

2024-10-10 23:55 UTC, christopherco commented on SPECS/vim/CVE-2024-43802.patch
> +index 0000000000000000000000000000000000000000..c40adbec4d07a66bcc9aa51e40dbbb90fdc36623
I see the upstream patch added a binary for testing. Is this binary diff actually correct?

2024-10-11 19:07 UTC, sameluch commented on SPECS/vim/CVE-2024-43802.patch
> +index 0000000000000000000000000000000000000000..c40adbec4d07a66bcc9aa51e40dbbb90fdc36623
removed binary diff portion of the patch for which is only for testing. added note to the patch description.

2024-10-14 21:25 UTC, christopherco approved these changes

2024-10-15 04:00 UTC, jslobodzian approved these changes

2024-10-16 16:05 UTC, rikenm1 requested changes
Sam, BuildAndtest Pr checked failed. It failed because one or more Ptests failed. Can you check to see if this failure has been happening for a while or if it is because of this new change.

2024-10-17 18:53 UTC, merged