Upgrade SuperLU version to 7.0.0
microsoft/azurelinux pull request #10744
Opened 2024-10-16 07:01 UTC by jykanase

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [ ] The toolchain has been rebuilt successfully (or no changes were made to it)
- [ ] The toolchain/worker package manifests are up-to-date
- [ ] Any updated packages successfully build (or no packages were changed)
- [ ] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [ ] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [ ] All package sources are available
- [ ] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [ ] LICENSE-MAP files are up-to-date (`./LICENSES-AND-NOTICES/SPECS/data/licenses.json`, `./LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md`, `./LICENSES-AND-NOTICES/SPECS/LICENSE-EXCEPTIONS.PHOTON`)
- [ ] All source files have up-to-date hashes in the `*.signatures.json` files
- [ ] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [ ] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

Upgrade SuperLU version to 7.0.0

###### Change Log  

-SPECS-EXTENDED/SuperLU/SuperLU.signatures.json
-SPECS-EXTENDED/SuperLU/SuperLU.spec
-cgmanifest.json

###### Does this affect the toolchain?  

**NO**

###### Associated issues  

- #xxxx

###### Links to CVEs  
- https://nvd.nist.gov/vuln/detail/CVE-YYYY-XXXX

###### Test Methodology

- Pipeline build id: xxxx

2024-11-18 09:16 UTC, suresh-thelkar commented
@jykanase, Can you please repush the changes so that the PR checks will run. Also verify the licenses by updating the corresponding markdown file by utilizing the script license_map.py

2024-11-18 09:17 UTC, suresh-thelkar reviewed
Please  look into the comment I have added.

2024-11-18 13:12 UTC, jykanase commented
updated

2024-11-19 04:38 UTC, suresh-thelkar reviewed
Please do not checkin the rpm log and test logs. Just attachem them to the PR as a proof of testing.

2024-11-20 11:25 UTC, suresh-thelkar requested changes

2024-11-28 05:20 UTC, suresh-thelkar commented
Here are the buddy build [results](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=685144&view=logs&j=bac295d9-f2e0-5165-e63e-e76f383e1a27&t=11f6dde0-e75e-52b2-fbf0-d83a00678fa3).

2024-11-28 05:21 UTC, suresh-thelkar approved these changes

2025-03-02 14:59 UTC, LeoMar4 approved these changes

2025-03-02 14:59 UTC, merged