Upgrade gphoto2 to 2.5.28-1
microsoft/azurelinux pull request #10776
Opened 2024-10-17 20:49 UTC by kevin-b-lockwood

Depends on https://github.com/microsoft/azurelinux/pull/10775
- Upgrade gphoto2 to latest upstream

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./LICENSES-AND-NOTICES/SPECS/data/licenses.json`, `./LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md`, `./LICENSES-AND-NOTICES/SPECS/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

Upgrade gphoto2 to latest upstream

###### Change Log  

- Simple version bump of gphoto2

###### Does this affect the toolchain?  

**NO**

###### Associated issues  

- N/A

###### Links to CVEs  
- N/A

###### Test Methodology

- Local build

2025-01-22 08:31 UTC, Sumynwa commented
Buddy Build Local run: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=712552&view=results

Test Install Rpms fail:
About to tdnf install package 'libgphoto2' ('libgphoto2-2.5.31-1.azl3.x86_64.rpm')
Loaded plugin: tdnfrepogpgcheck
1. nothing provides liblockdev.so.1()(64bit) needed by libgphoto2-2.5.31-1.azl3.x86_64
Found 1 problem(s) while resolving

2025-01-22 08:32 UTC, Sumynwa requested changes

2025-02-14 22:01 UTC, kevin-b-lockwood commented on SPECS-EXTENDED/gphoto2/gphoto2.spec
> +Version:        2.5.28
Will do (Sorry so slow). Bear in mind that this package will not build until the libgphoto2 PR is merged in.

2025-03-13 07:40 UTC, Sumynwa requested changes

2025-03-13 07:40 UTC, Sumynwa commented on SPECS-EXTENDED/gphoto2/gphoto2.signatures.json
> -}
Please fix no new line error

2025-04-11 06:01 UTC, Sumynwa commented
> Buddy Build Local run: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=712552&view=results
> 
> Test Install Rpms fail: About to tdnf install package 'libgphoto2' ('libgphoto2-2.5.31-1.azl3.x86_64.rpm') Loaded plugin: tdnfrepogpgcheck
> 
> 1. nothing provides liblockdev.so.1()(64bit) needed by libgphoto2-2.5.31-1.azl3.x86_64
>    Found 1 problem(s) while resolving

https://github.com/microsoft/azurelinux/pull/10775 has been merged. This should provide the failing dependency.

2025-06-26 06:19 UTC, Sumynwa requested changes

2025-06-26 06:19 UTC, Sumynwa commented on cgmanifest.json
> +          "downloadUrl": "http://downloads.sourceforge.net/gphoto/gphoto2-2.5.28.tar.bz2"
Kindly switch to https.

2025-08-04 21:15 UTC, kevin-b-lockwood commented
@Sumynwa I believe the only thing this PR needs is to have a buddy build. Would you mind helping me get that kicked off? Thanks.

2026-05-17 05:00 UTC, closed without merging