exiv2: Update to version 0.28.3
microsoft/azurelinux pull request #10820
Opened 2024-10-23 09:51 UTC by jykanase

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [ ] The toolchain has been rebuilt successfully (or no changes were made to it)
- [ ] The toolchain/worker package manifests are up-to-date
- [ ] Any updated packages successfully build (or no packages were changed)
- [ ] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [ ] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [ ] All package sources are available
- [ ] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [ ] LICENSE-MAP files are up-to-date (`./LICENSES-AND-NOTICES/SPECS/data/licenses.json`, `./LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md`, `./LICENSES-AND-NOTICES/SPECS/LICENSE-EXCEPTIONS.PHOTON`)
- [ ] All source files have up-to-date hashes in the `*.signatures.json` files
- [ ] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [ ] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

exiv2: Update to version 0.28.3

###### Change Log  

-SPECS-EXTENDED/exiv2/exiv2.signatures.json
-SPECS-EXTENDED/exiv2/exiv2.spec
-cgmanifest.json

###### Does this affect the toolchain?  

**NO**

###### Associated issues  

- #xxxx

###### Links to CVEs  
- https://nvd.nist.gov/vuln/detail/CVE-YYYY-XXXX

###### Test Methodology

- Pipeline build id: xxxx

2025-01-22 08:50 UTC, Sumynwa commented
Buddy Build run: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=712528&view=results PASS

2025-01-22 08:51 UTC, Sumynwa requested changes

2025-01-22 08:51 UTC, Sumynwa commented on SPECS-EXTENDED/exiv2/exiv2.spec
> +#%make install/fast DESTDIR=%{buildroot}
Remove the commented line if not needed

2025-01-22 08:56 UTC, jykanase commented on SPECS-EXTENDED/exiv2/exiv2.spec
> +#%make install/fast DESTDIR=%{buildroot}
Updated the changes

2025-02-07 06:27 UTC, Sumynwa approved these changes
LGTM. Thanks.

2025-03-02 14:56 UTC, LeoMar4 approved these changes

2025-03-02 14:56 UTC, merged