Base Version: Updating Azure-Linux: Import from Fedora 42 version 0.2…
microsoft/azurelinux pull request #10907
Opened 2024-11-01 09:44 UTC by v-smalavathu

…0140727.

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./LICENSES-AND-NOTICES/SPECS/data/licenses.json`, `./LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md`, `./LICENSES-AND-NOTICES/SPECS/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [x] Ready to merge

---

###### Summary 

Updating Azure-Linux: Import from Fedora 42 version 0.20140727.

###### Change Log  

- Updating Azure-Linux: Import from Fedora 42 version 0.20140727.

###### Does this affect the toolchain?  

No

###### Associated issues  

- #xxxx

###### Links to CVEs  
- https://nvd.nist.gov/vuln/detail/CVE-YYYY-XXXX

###### Test Methodology

- Pipeline build id: xxxx

2025-03-05 10:26 UTC, suresh-thelkar requested changes
Most of the code changes look good to me. Some PR checks are failing. Can you please take a look.

2025-03-05 16:34 UTC, v-smalavathu commented
> Most of the code changes look good to me. Some PR checks are failing. Can you please take a look.

Yes, "Fixed cgmanifest file".
Now PR Checks are successful except PR Check 'Upload the zip file to Blob Store" that occurs after approval.
-Thanks

2025-03-13 16:00 UTC, v-smalavathu commented
@ Buddy Build run:
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=755287&view=results

Here, I installed Package: 'hyphen-pt' manually on docker image: 'azurelinux/base/core:3.0' with dependency packages. it is successful.

Here, attaching logs.
-Thanks

[Install-Package-Hyphen-pt-in-Docker.txt](https://github.com/user-attachments/files/19232408/Install-Package-Hyphen-pt-in-Docker.txt)

2025-03-17 11:29 UTC, suresh-thelkar approved these changes
thanks for making the changes.

2026-05-17 05:01 UTC, closed without merging