Updating to Azure-Linux import from Fedora 41
microsoft/azurelinux pull request #10957
Opened 2024-11-06 17:27 UTC by v-smalavathu

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./LICENSES-AND-NOTICES/SPECS/data/licenses.json`, `./LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md`, `./LICENSES-AND-NOTICES/SPECS/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [x] Ready to merge

---

###### Summary 

Updating to Azure-Linux import from Fedora 41

###### Change Log  

- Updating to Azure-Linux import from Fedora 41

###### Does this affect the toolchain?  

NO

###### Associated issues  

- #xxxx

###### Links to CVEs  
- https://nvd.nist.gov/vuln/detail/CVE-YYYY-XXXX

###### Test Methodology

- Pipeline build id: xxxx

2025-03-10 08:58 UTC, Sumynwa requested changes

2025-03-10 08:58 UTC, Sumynwa commented on SPECS-EXTENDED/hyphen-it/hyphen-it.signatures.json
> +}
Please fix no new line error

2025-03-10 08:58 UTC, Sumynwa commented
Buddy Build Run: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=756612&view=results

Test Install rpms is failing

2025-03-11 14:13 UTC, v-smalavathu commented on SPECS-EXTENDED/hyphen-it/hyphen-it.signatures.json
> +}
Fixed the issue,

2025-03-11 15:19 UTC, v-smalavathu commented
> Buddy Build Run: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=756612&view=results
> 
> Test Install rpms is failing

Here, I installed Package: 'hyphen-it' manually on 
docker image: 'azurelinux/base/core:3.0' and
instaled dependency packages and desired package
and it is successful.

Here, attaching logs.
-Thanks
[Install-Package-Hyphen-IT-in-Docker.txt](https://github.com/user-attachments/files/19187284/Install-Package-Hyphen-IT-in-Docker.txt)

2025-03-13 07:43 UTC, Sumynwa approved these changes

2025-04-11 07:31 UTC, 0xba1a approved these changes

2025-04-11 07:31 UTC, merged