OSModifier: Add services, modules, and kernel cmdline in EMU API
microsoft/azurelinux pull request #11080
Opened 2024-11-14 21:01 UTC by elainezhao96

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [ ] The toolchain has been rebuilt successfully (or no changes were made to it)
- [ ] The toolchain/worker package manifests are up-to-date
- [ ] Any updated packages successfully build (or no packages were changed)
- [ ] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [ ] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [ ] All package sources are available
- [ ] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [ ] LICENSE-MAP files are up-to-date (`./LICENSES-AND-NOTICES/SPECS/data/licenses.json`, `./LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md`, `./LICENSES-AND-NOTICES/SPECS/LICENSE-EXCEPTIONS.PHOTON`)
- [ ] All source files have up-to-date hashes in the `*.signatures.json` files
- [ ] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [ ] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

What does the PR accomplish, why was it needed?

###### Change Log  

- Change
- Change
- Change

###### Does this affect the toolchain?  

**YES/NO**

###### Associated issues  

- #xxxx

###### Links to CVEs  
- https://nvd.nist.gov/vuln/detail/CVE-YYYY-XXXX

###### Test Methodology

- Pipeline build id: xxxx

2024-11-16 00:03 UTC, cwize1 requested changes

2024-11-16 00:03 UTC, cwize1 commented on toolkit/tools/pkg/imagecustomizerlib/typeConversion.go
> +		ExtraCommandLine: strings.Join(kernelCommandLine.ExtraCommandLine, " "),
Use the `GrubArgsToString` function to convert the list to a escaped/quoted string.

2024-11-21 16:51 UTC, elainezhao96 commented on toolkit/tools/imagecustomizerapi/kernelextraarguments.go
> +type KernelExtraArguments []string
I kept the 'kernel command-line as a list' change  in this pr and moved the rest to https://github.com/microsoft/azurelinux/pull/11153

2024-11-21 16:51 UTC, elainezhao96 commented on toolkit/tools/imagecustomizerapi/kernelextraarguments.go
> +		err := validateKernelArgumentsFormat(arg)
removed the KernelExtraArguments type and its related tests (for testing unmatched quotes)

2024-11-21 16:57 UTC, elainezhao96 commented on toolkit/tools/imagecustomizerapi/iso_test.go
>  func TestIsoIsValid(t *testing.T) {
Should I delete this or not?

2024-11-21 20:03 UTC, cwize1 requested changes

2024-12-06 08:03 UTC, elainezhao96 commented on toolkit/tools/imagecustomizerapi/kernelextraarguments.go
>  	"strings"
you're right, this file can be deleted

2024-12-06 19:48 UTC, elainezhao96 commented on toolkit/tools/pkg/imagecustomizerlib/liveosisobuilder.go
> +	savedArgs := strings.Join(savedConfigs.Iso.KernelCommandLine.ExtraCommandLine, " ")
addressed in new pr https://github.com/microsoft/azure-linux-image-tools/pull/19

2024-12-06 19:48 UTC, elainezhao96 commented on toolkit/tools/imagecustomizerapi/os_test.go
> -func TestOSIsValidInvalidKernelCommandLine(t *testing.T) {
addressed in https://github.com/microsoft/azure-linux-image-tools/pull/19

2024-12-06 19:49 UTC, elainezhao96 commented on toolkit/tools/pkg/imagecustomizerlib/liveosisobuilder_test.go
> +	assert.Equal(t, "rd.info rd.debug", strings.Join(savedConfigs.Iso.KernelCommandLine.ExtraCommandLine, " "))
addressed in https://github.com/microsoft/azure-linux-image-tools/pull/19

2026-05-14 07:21 UTC, closed without merging