Upgrades lua-lpeg to version 1.1.0
microsoft/azurelinux pull request #11167
Opened 2024-11-20 20:33 UTC by aninda-al

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./LICENSES-AND-NOTICES/SPECS/data/licenses.json`, `./LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md`, `./LICENSES-AND-NOTICES/SPECS/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

Upgrades lua lpeg to version 1.1.0

###### Build/Dependency Information 
Please build following packages with lua-lpeg:
compat-lua

###### Change Log  

- modified: SPECS-EXTENDED/lua-lpeg/lua-lpeg.signatures.json
- modified: SPECS-EXTENDED/lua-lpeg/lua-lpeg.spec
- modified: cgmanifest.json

###### Does this affect the toolchain?  

**NO**

###### Associated issues  

- NA

###### Links to CVEs  
- NA

###### Test Methodology

- local build
- docker install 
<img width="834" height="261" alt="image" src="https://github.com/user-attachments/assets/e045e9a4-0e5c-4b82-821c-a46ad91621f2" />

2025-04-14 12:50 UTC, kgodara912 requested changes

2025-04-14 13:01 UTC, aninda-al commented on cgmanifest.json
> +          "downloadUrl": "https://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.1.0.tar.gz"
sha256sum value of both  https://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.1.0.tar.gz & https://github.com/neovim/deps/blob/master/opt/lpeg-1.1.0.tar.gz are same [4b155d67d2246c1ffa7ad7bc466c1ea899bbc40fef0257cc9c03cecbaed4352a]

2025-04-14 16:14 UTC, aninda-al commented on cgmanifest.json
> +          "downloadUrl": "https://www.inf.puc-rio.br/~roberto/lpeg/lpeg-1.1.0.tar.gz"
corrected the download and source urls

2025-04-24 17:29 UTC, kgodara912 commented on SPECS-EXTENDED/lua-lpeg/lua-lpeg.spec
> +* Thu Feb 27 2025 Aninda Pradhan <v-anipradhan@microsoft.com> - 1.1.0-3
May be Release number 2 instead of 3
else good for next stage: buddy build pipeline.

2025-04-24 21:08 UTC, aninda-al commented on SPECS-EXTENDED/lua-lpeg/lua-lpeg.spec
> +* Thu Feb 27 2025 Aninda Pradhan <v-anipradhan@microsoft.com> - 1.1.0-3
corrected the release number

2026-05-17 05:02 UTC, closed without merging