upgrade rust to 1.83.0
microsoft/azurelinux pull request #11295
Opened 2024-12-03 11:24 UTC by KavyaSree2610

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [ ] The toolchain has been rebuilt successfully (or no changes were made to it)
- [ ] The toolchain/worker package manifests are up-to-date
- [ ] Any updated packages successfully build (or no packages were changed)
- [ ] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [ ] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [ ] All package sources are available
- [ ] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [ ] LICENSE-MAP files are up-to-date (`./LICENSES-AND-NOTICES/SPECS/data/licenses.json`, `./LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md`, `./LICENSES-AND-NOTICES/SPECS/LICENSE-EXCEPTIONS.PHOTON`)
- [ ] All source files have up-to-date hashes in the `*.signatures.json` files
- [ ] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [ ] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

What does the PR accomplish, why was it needed?

###### Change Log  

- Change
- Change
- Change

###### Does this affect the toolchain?  

**YES/NO**

###### Associated issues  

- #xxxx

###### Links to CVEs  
- https://nvd.nist.gov/vuln/detail/CVE-YYYY-XXXX

###### Test Methodology

- Pipeline build id: xxxx

2025-01-06 05:58 UTC, mfrw reviewed
Can we please skip the failing tests, so that the pipeline is green.
Let's add a link where we skip to the FreeBSD forum to clarify on why are we even skiping :)

2025-03-13 22:59 UTC, ms-mahuber commented on SPECS/clamav/clamav.spec
>  # Note: Required an updated cargo cache when rust was updated to 1.72.0, added "-rev2" to the filename to indicate the new cache for this
This comment seems out of date and now wrong, but it is highly related. We should adapt the comment according to what we have done here.

2025-03-13 23:00 UTC, ms-mahuber commented on SPECS/clamav/clamav.spec
> +* Fri Mar 07 2025 Kavya Sree Kaitepalli <kkaitepalli@microsoft.com> -1.0.7-2
empty space. missing. please run SPEC sanitization tooling, if not done, to catch such things

2025-03-13 23:02 UTC, ms-mahuber commented on SPECS/flux/flux.spec
> -%patch 2 -p1
Potential for optimization but fine with me

2025-03-13 23:04 UTC, ms-mahuber commented on cgmanifest.json
> -          "downloadUrl": "https://static.rust-lang.org/dist/rustc-1.75.0-src.tar.xz"
do we need to change cgmanifest for clamav as well?

2025-03-13 23:09 UTC, ms-mahuber commented on SPECS/rust/rust.spec
> +rm -f %{buildroot}%{_docdir}/rustc/{COPYRIGHT,LICENSE-APACHE,LICENSE-MIT}
is -f potentially only required when running locally?

2025-03-13 23:10 UTC, Camelron commented on SPECS/rust/rust.signatures.json
> +  "cargo-1.84.0-aarch64-unknown-linux-gnu.tar.xz": "68d4ad239b6d1e810e7b8591636dc408cb2c1e89661329fed906febf9c0a9d98",
Ah, after more reading I see the stage0 stuff in the spec. Seems to indeed be bootstrapping.

2025-03-13 23:13 UTC, Camelron commented on SPECS/rust/Remove_cannot_write_error_test.patch
> +-cannot_write_error() {
Why are we removing some of these tests?

2025-03-13 23:16 UTC, ms-mahuber commented on SPECS/rust/rust.signatures.json
> +  "cargo-1.84.0-aarch64-unknown-linux-gnu.tar.xz": "68d4ad239b6d1e810e7b8591636dc408cb2c1e89661329fed906febf9c0a9d98",
Interesting that only the rustc-1.84.0-src.tar.xz is present in cmanifest.

By the way, it should be 1.85 in cgmanifest.json

2025-03-13 23:29 UTC, corvus-callidus commented on SPECS/flux/flux.spec
> -%patch 2 -p1
Is there a good reason for continuing to use %setup and %patch here instead of changing to %autosetup?

2025-03-13 23:39 UTC, Camelron approved these changes
lgtm

2025-03-14 00:11 UTC, Camelron commented on SPECS/rust/rust.signatures.json
> +  "cargo-1.84.0-aarch64-unknown-linux-gnu.tar.xz": "68d4ad239b6d1e810e7b8591636dc408cb2c1e89661329fed906febf9c0a9d98",
I saw that too; I think it is for bootstrapping the compiler (since you compile rust from rust..) https://github.com/microsoft/azurelinux/pull/11295#discussion_r1994411533

2025-03-17 05:30 UTC, KavyaSree2610 commented on SPECS/clamav/clamav.spec
>  # Note: Required an updated cargo cache when rust was updated to 1.72.0, added "-rev2" to the filename to indicate the new cache for this
Updated the comment

2025-03-17 05:53 UTC, KavyaSree2610 commented on cgmanifest.json
> -          "downloadUrl": "https://static.rust-lang.org/dist/rustc-1.75.0-src.tar.xz"
I believe there is no need to modify the cgmanifest for clamav, as we are not updating or changing the sources of any other packages.

2025-03-17 06:25 UTC, mfrw commented on SPECS/rust/rust.signatures.json
> +  "cargo-1.84.0-aarch64-unknown-linux-gnu.tar.xz": "68d4ad239b6d1e810e7b8591636dc408cb2c1e89661329fed906febf9c0a9d98",
Yes, correct. it is for bootstrapping :)

2025-03-17 06:25 UTC, mfrw approved these changes
LGTM :)
🥇

2025-03-17 08:30 UTC, KavyaSree2610 commented on SPECS/flux/flux.spec
> -%patch 2 -p1
Updated it to %autosetup

2025-03-17 17:52 UTC, ms-mahuber commented on cgmanifest.json
> -          "downloadUrl": "https://static.rust-lang.org/dist/rustc-1.75.0-src.tar.xz"
I see, for this package we just re-vendored

2025-03-17 18:00 UTC, ms-mahuber commented on SPECS/rust/rust.signatures.json
> +  "cargo-1.84.0-aarch64-unknown-linux-gnu.tar.xz": "68d4ad239b6d1e810e7b8591636dc408cb2c1e89661329fed906febf9c0a9d98",
To get clarity whether some of the reference tar balls should be present in cgmanifest.json. e.g., why does `rust-std-1.84.0-aarch64-unknown-linux-gnu.tar.xz` not need to be mentioned?

2025-03-17 18:05 UTC, ms-mahuber commented on SPECS/rust/rust.spec
> +Patch0:		Remove_cannot_write_error_test.patch
Patch0, 1: Re-verify if these fail in the pipeline. Both seem to have a similar issue (expect permission issues are revoking permissions with chmod, but the expected-to-fail commands still work)

2025-03-17 18:08 UTC, ms-mahuber commented on SPECS/rust/rust.spec
> +Patch2:		Ignore_failing_ci_tests.patch
Let's specify which CI tests fail and re-assess

2025-03-17 18:10 UTC, ms-mahuber commented on SPECS/rust/rust.spec
> +Patch4:		Ignore-test-for-aarch64.patch
error: linker `aarch64-linux-gnu-gcc` not found. Let's assess whether this is expected to fail for Azure Linux or e.g. whether the linker binary would need to be renamed.

Side note: Let's add some documentation for all the patch files we add. This way it becomes clear why we did this

2025-03-17 21:02 UTC, ms-mahuber commented on SPECS/rust/Remove_cannot_write_error_test.patch
> +-cannot_write_error() {
Refined comments per patch

2025-03-17 21:06 UTC, Camelron requested changes
In retrospect, we should get to the bottom of why these patches removing tests are required before proceeding.

2025-04-01 07:13 UTC, KavyaSree2610 commented on SPECS/rust/rust.spec
> +rm -f %{buildroot}%{_docdir}/rustc/{COPYRIGHT,LICENSE-APACHE,LICENSE-MIT}
Removed -f

2025-04-01 07:15 UTC, KavyaSree2610 commented on SPECS/rust/rust.spec
> -Version:        1.75.0
Bumped all packages

2025-04-01 07:17 UTC, KavyaSree2610 commented on SPECS/rust/rust.signatures.json
> +  "cargo-1.84.0-aarch64-unknown-linux-gnu.tar.xz": "68d4ad239b6d1e810e7b8591636dc408cb2c1e89661329fed906febf9c0a9d98",
Only the source0 tarballs needs to be present in cgmanifest and that is why the other sources are not present

2025-04-01 07:18 UTC, KavyaSree2610 commented on SPECS/rust/rust.spec
> +Patch0:		Remove_cannot_write_error_test.patch
Test passed when run as non-root user

2025-04-01 07:19 UTC, KavyaSree2610 commented on SPECS/rust/rust.spec
> +Patch3:		skip-failing-run-make-tests.patch
run-make tests passed when run as non-root user

2025-04-01 22:35 UTC, ms-mahuber commented on SPECS/clamav/clamav.spec
> +
nit: no need

2025-04-01 22:35 UTC, ms-mahuber commented on SPECS/rust/rust.spec
> +BuildRequires:	sudo
Why exactly is this required?

2025-04-01 22:35 UTC, ms-mahuber commented on SPECS/rust/rust.spec
> -./x.py run src/tools/expand-yaml-anchors
Why do we no longer need this?

2025-04-01 22:35 UTC, ms-mahuber commented on SPECS/rust/rust.spec
> -%make_build check
can we comment on the reason we removed this line and instead use a different pattern?

2025-04-01 22:35 UTC, ms-mahuber commented on SPECS/rust/rust.spec
>  # remove rustdoc ui flaky test issue-98690.rs (which is tagged with 'unstable-options')
the comment can be removed as well right?

2025-04-01 22:35 UTC, ms-mahuber commented on SPECS/rust/rust.spec
> +#Patch1:		Ignore-test-for-aarch64.patch
Is this because our investigation on this is pending?

2025-04-01 22:39 UTC, ms-mahuber commented
As the PR progresses, can we please post up to date pipeline links for all affected packages, showing build and package tests to behave according to our findings?

2025-04-02 04:23 UTC, KavyaSree2610 commented on SPECS/rust/rust.spec
> +BuildRequires:	sudo
Since we are now running the tests using non root user and we are using sudo -u for this, so this was required

2025-04-02 04:27 UTC, KavyaSree2610 commented on SPECS/rust/rust.spec
> -./x.py run src/tools/expand-yaml-anchors
expand-yaml-anchors tool was removed from upstream
Reference: https://github.com/rust-lang/rust/commit/0b1ecf1d8d9318eedf68c855ac1112f0063dd495

2025-04-02 07:16 UTC, KavyaSree2610 commented on SPECS/rust/rust.spec
>  # remove rustdoc ui flaky test issue-98690.rs (which is tagged with 'unstable-options')
We are not removing test issue-98690.rs , it is still flaky

2025-04-02 15:23 UTC, KavyaSree2610 commented on SPECS/rust/rust.spec
> +#Patch1:		Ignore-test-for-aarch64.patch
yes, now this ptest is passing after adding a symlink between `aarch64-unknown-linux-gnu-gcc` and `aarch64-linux-gnu-gcc`

2025-04-02 15:59 UTC, ms-mahuber commented on SPECS/clamav/clamav.spec
>  # To update the cache run:
Need to revisit this comment. How were the vendor sources re-created for this update?

2025-04-02 18:47 UTC, ms-mahuber commented on SPECS-EXTENDED/389-ds-base/389-ds-base.spec
> +* Tue Apr 01 2025 Kavya Sree Kaitepalli <kkaitepalli@microsoft.com> 3.1.0-3
We should also bump cloud-hypervisor-cvm.

For kata-containers, kata-containers-cc we need to upgrade our sources. Hence, we need to not upgrade the minor version to avoid a re-build. but likely we should version-pin those two packages to the prior version

2025-04-02 23:52 UTC, ms-mahuber commented on SPECS/rust/rust.spec
> -%doc %{_docdir}/%{name}/html/*
I am seeing this when building, at least in my environment: WARN: (rust-doc-1.85.0-1.azl3.noarch.rpm) has license warning

2025-04-03 00:16 UTC, ms-mahuber commented on SPECS/rust/rust.spec
>  Name:           rust
Going through package build logs, I am seeing various errors/warnings that we should at least confirm to be benign. Seeing things like:

```
time="2025-04-02T23:23:59Z" level=debug msg="[2025-04-02T23:23:38Z WARN  mdbook::preprocess::cmd] The command wasn't found, is the \"spec\" preprocessor installed?"
time="2025-04-02T23:23:59Z" level=debug msg="[2025-04-02T23:23:38Z WARN  mdbook::preprocess::cmd] \tCommand: cargo run --release --manifest-path mdbook-spec/Cargo.toml"
...
time="2025-04-02T23:23:59Z" level=debug msg="[2025-04-02T23:23:40Z WARN  mdbook::preprocess::cmd] The command wasn't found, is the \"gettext\" preprocessor installed?"
time="2025-04-02T23:23:59Z" level=debug msg="[2025-04-02T23:23:40Z WARN  mdbook::preprocess::cmd] \tCommand: mdbook-gettext"
time="2025-04-02T23:23:59Z" level=debug msg="   0.485361953s  INFO prepare_target{force=false package_id=lint-docs v0.1.0 (/usr/src/azl/BUILD/rustc-1.85.0-src/src/tools/lint-docs) target=\"lint_docs\"}: cargo::core::compiler::fingerprint: fingerprint error for lint-docs v0.1.0 (/usr/src/azl/BUILD/rustc-1.85.0-src/src/tools/lint-docs)/Build/TargetInner { name_inferred: true, ..: lib_target(\"lint_docs\", [\"lib\"], \"/usr/src/azl/BUILD/rustc-1.85.0-src/src/tools/lint-docs/src/lib.rs\", Edition2021) }"
time="2025-04-02T23:23:59Z" level=debug msg="   0.485384278s  INFO prepare_target{force=false package_id=lint-docs v0.1.0 (/usr/src/azl/BUILD/rustc-1.85.0-src/src/tools/lint-docs) target=\"lint_docs\"}: cargo::core::compiler::fingerprint:     err: failed to read `/usr/src/azl/BUILD/rustc-1.85.0-src/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/.fingerprint/lint-docs-ea2c53b2da5f5e99/lib-lint_docs`"
time="2025-04-02T23:23:59Z" level=debug
time="2025-04-02T23:23:59Z" level=debug msg="Caused by:"
time="2025-04-02T23:23:59Z" level=debug msg="    No such file or directory (os error 2)"
time="2025-04-02T23:23:59Z" level=debug msg="   0.485483381s  INFO prepare_target{force=false package_id=serde_json v1.0.134 target=\"serde_json\"}: cargo::core::compiler::fingerprint: fingerprint error for serde_json v1.0.134/Build/TargetInner { doc_scrape_examples: Disabled, ..: lib_target(\"serde_json\", [\"lib\"], \"/usr/src/azl/BUILD/rustc-1.85.0-src/vendor/serde_json-1.0.134/src/lib.rs\", Edition2021) }"
time="2025-04-02T23:23:59Z" level=debug msg="   0.485489824s  INFO prepare_target{force=false package_id=serde_json v1.0.134 target=\"serde_json\"}: cargo::core::compiler::fingerprint:     err: failed to read `/usr/src/azl/BUILD/rustc-1.85.0-src/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/.fingerprint/serde_json-79f638edf9421942/lib-serde_json`"
time="2025-04-02T23:23:59Z" level=debug
```

We should iterate over the logs

2025-04-03 15:42 UTC, ms-mahuber commented on SPECS-EXTENDED/389-ds-base/389-ds-base.spec
> +* Tue Apr 01 2025 Kavya Sree Kaitepalli <kkaitepalli@microsoft.com> 3.1.0-3
For kata-containers, kata-containers-cc: "BuildRequires:  rust <= 1.75.0"

2025-04-03 15:56 UTC, ms-mahuber commented on SPECS/rust/rust.spec
> -%doc %{_docdir}/%{name}/html/*
Discussed to revisit internally. The rust-doc package has a lot of file that are being flagged as bad doc files ....

2025-04-03 15:58 UTC, ms-mahuber commented on SPECS/rust/rust.spec
> +mv %{buildroot}%{_docdir}/cargo/LICENSE-THIRD-PARTY .
This looks a bit odd. But without removals, this results in:
duplicated license files:
		/usr/share/doc/cargo/LICENSE-APACHE
		/usr/share/doc/cargo/LICENSE-MIT
		/usr/share/doc/clippy/LICENSE-APACHE
		/usr/share/doc/clippy/LICENSE-MIT
		/usr/share/doc/rustfmt/LICENSE-APACHE
		/usr/share/doc/rustfmt/LICENSE-MIT

2025-04-03 16:12 UTC, ms-mahuber commented on SPECS/rust/rust.spec
> +mv %{buildroot}%{_docdir}/cargo/LICENSE-THIRD-PARTY .
Related: https://github.com/microsoft/azurelinux/pull/13059/files

2025-04-09 08:40 UTC, KavyaSree2610 commented
> In retrospect, we should get to the bottom of why these patches removing tests are required before proceeding.

done with the investigation of the tests

2025-04-09 16:25 UTC, Camelron approved these changes

2025-04-14 22:21 UTC, ms-mahuber commented on SPECS/flux/flux.spec
>  Summary:        Influx data language
Please see: https://github.com/microsoft/azurelinux/pull/13385/files

2025-04-14 23:19 UTC, tobiasb-ms requested changes

2025-04-14 23:19 UTC, tobiasb-ms commented on SPECS/flux/0001-flux-enable-build-with-rust-1.85.0.patch
> + libflux/flux-core/src/ast/walk/mod.rs   | 2 +-
The changes for `ast/walk/mod.rs` and `parser/mod.rs` are both identical to the changes from this upstream PR: https://github.com/influxdata/flux/pull/5516.

You should probably call that PR out in the comments in this patch and/or where you apply it so we know where it comes from and when we can remove it.

2025-04-14 23:19 UTC, tobiasb-ms commented on SPECS/flux/0001-flux-enable-build-with-rust-1.85.0.patch
> ++#[allow(dead_code)]
Take a look at upstream https://github.com/influxdata/flux/pull/5484, which fixes a number of issues required for rust 1.78. They do a more focused application of `allow(dead_code)`. If that works, I'd prefer to keep it closer to what upstream does (and mention the PR in the patch comments and/or spec file).

2025-04-15 14:45 UTC, tobiasb-ms requested changes

2025-04-15 14:45 UTC, tobiasb-ms commented on SPECS/flux/flux.spec
> +Patch4:		0001-Fix-with-latest-rust.patch
nit: Please fix spacing.

2025-04-15 14:45 UTC, tobiasb-ms commented on SPECS/flux/flux.spec
> -%patch 2 -p1
I notice that you switched back away from `%autosetup`.

I don't mind this, because it keeps us closer to the [OpenSUSE upstream](https://build.opensuse.org/projects/openSUSE:Factory/packages/flux/files/flux.spec?expand=1), but I wanted to make sure that's intentional.

2025-04-15 14:45 UTC, tobiasb-ms commented on SPECS/flux/flux.spec
> -patch -p2 < %{PATCH1}
Looks like we're no longer applying `PATCH1`.

2025-04-15 14:45 UTC, tobiasb-ms commented on SPECS/flux/flux.spec
> +
nit: remove extra blank line.

2025-04-15 14:54 UTC, KavyaSree2610 commented on SPECS/flux/flux.spec
> -patch -p2 < %{PATCH1}
Removed it mistakenly, adding it again

2025-04-23 22:38 UTC, jslobodzian commented on SPECS/rust/rust.spec
> +%define stage0_version 1.84.0
Is the 1.74.0 version capable of building the 1.85 version?

2025-04-24 00:36 UTC, KavyaSree2610 commented on SPECS/rust/rust.spec
> +%define stage0_version 1.84.0
> Is the 1.74.0 version capable of building the 1.85 version?

No, it should be built with 1.84

2025-04-24 17:06 UTC, jslobodzian approved these changes

2025-04-24 22:15 UTC, merged