grpc: Address CVE-2023-32067
microsoft/azurelinux pull request #11394
Opened 2024-12-10 13:41 UTC by Ankita13-code

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./LICENSES-AND-NOTICES/SPECS/data/licenses.json`, `./LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md`, `./LICENSES-AND-NOTICES/SPECS/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [x] Ready to merge

---

###### Summary 

What does the PR accomplish, why was it needed?
This PR addresses CVE-2023-32067 for grpc submodules package.

###### Change Log  

- Add formatted patch for this CVE
- Upstream patch - [CVE-2023-32067 patch](https://github.com/c-ares/c-ares/commit/b9b8413cfdb70a3f99e1573333b23052d57ec1ae)

###### Does this affect the toolchain?  

**NO**

###### Associated issues  

- #xxxx

###### Links to CVEs  
- https://nvd.nist.gov/vuln/detail/CVE-2023-32067

###### Test Methodology

- Pipeline build id: xxxx

2024-12-18 14:15 UTC, jslobodzian commented on SPECS/grpc/grpc.spec
> +%patch0 -p1
@Ankita13-code prefer updating to %autopatch -p1 in this situation.

2024-12-19 17:32 UTC, rikenm1 requested changes

2024-12-19 17:32 UTC, rikenm1 commented on SPECS/grpc/grpc.spec
> +%patch0 -p1
```suggestion
%autopatch -p1
```

2024-12-19 17:55 UTC, rikenm1 approved these changes
LGTM

2024-12-20 18:23 UTC, jslobodzian approved these changes

2024-12-20 18:26 UTC, merged

2024-12-20 18:34 UTC, nicogbg commented
Auto cherry-pick results:
- main :white_check_mark: -> https://github.com/microsoft/azurelinux/pull/11605

Auto cherry-pick pipeline run -> https://dev.azure.com/mariner-org/mariner/_build/results?buildId=697908&view=results