Updating CBL-Mariner import Fedora 41 (Version 0.13 -> 0.15).
microsoft/azurelinux pull request #11476
Opened 2024-12-17 00:59 UTC by v-smalavathu

- Added "License verified" statement to the changelog.

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./LICENSES-AND-NOTICES/SPECS/data/licenses.json`, `./LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md`, `./LICENSES-AND-NOTICES/SPECS/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [x] Ready to merge

---

###### Summary 

Updating CBL-Mariner import Fedora 41 (Version 0.13 -> 0.15).
- Added "License verified" statement to the changelog.

###### Change Log  

- Updating CBL-Mariner import Fedora 41 (Version 0.13 -> 0.15).
- Added "License verified" statement to the changelog.

###### Does this affect the toolchain?  

NO

###### Associated issues  

- #xxxx

###### Links to CVEs  
- https://nvd.nist.gov/vuln/detail/CVE-YYYY-XXXX

###### Test Methodology

- Pipeline build id: xxxx

2025-02-21 10:41 UTC, Sumynwa requested changes

2025-02-21 10:41 UTC, Sumynwa commented on SPECS-EXTENDED/perl-MRO-Compat/perl-MRO-Compat.signatures.json
> +}
Fix no new line error

2025-02-21 10:41 UTC, Sumynwa commented
Buddy Build run: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=708625&view=results

2025-02-21 17:59 UTC, v-smalavathu commented on SPECS-EXTENDED/perl-MRO-Compat/perl-MRO-Compat.signatures.json
> +}
Yes, Fixed the issue.

2025-02-28 07:37 UTC, Sumynwa approved these changes

2025-03-02 14:28 UTC, LeoMar4 approved these changes

2025-03-02 14:28 UTC, merged