nilfs-utils: update to 2.2.11
microsoft/azurelinux pull request #11487
Opened 2024-12-17 06:58 UTC by durgajagadeesh

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./LICENSES-AND-NOTICES/SPECS/data/licenses.json`, `./LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md`, `./LICENSES-AND-NOTICES/SPECS/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [x] Ready to merge

---

###### Summary 

nilfs-utils: update to 2.2.11

###### Build/Dependency Information 
The PR is a leaf PR which builds alone successfully.

###### Change Log  

../SPECS-EXTENDED/nilfs-utils/nilfs-utils.signatures.json
../SPECS-EXTENDED/nilfs-utils/nilfs-utils.spec
../cgmanifest.json
[nilfs-utils-2.2.11-3.azl3.src.rpm.log](https://github.com/user-attachments/files/18293481/nilfs-utils-2.2.11-3.azl3.src.rpm.log)
6

###### Does this affect the toolchain?  

**NO**

###### Associated issues  

- #xxxx

###### Links to CVEs  
- https://nvd.nist.gov/vuln/detail/CVE-YYYY-XXXX

###### Test Methodology

- Pipeline build id: xxxx

2024-12-26 06:20 UTC, suresh-thelkar commented on SPECS-EXTENDED/nilfs-utils/nilfs-utils.spec
>  %setup -q
Can we use autosetup macro here.

2025-01-02 18:39 UTC, durgajagadeesh commented on SPECS-EXTENDED/nilfs-utils/nilfs-utils.spec
>  %setup -q
yes,
tested with the autosetup macro.
built successfully.

2025-01-03 11:04 UTC, suresh-thelkar commented on cgmanifest.json
> +          "downloadUrl": "http://nilfs.sourceforge.net/download/nilfs-utils-2.2.11.tar.bz2"
Use https URL. Without which we cannot upload it to our blob store.

2025-01-06 05:39 UTC, durgajagadeesh commented on cgmanifest.json
> +          "downloadUrl": "http://nilfs.sourceforge.net/download/nilfs-utils-2.2.11.tar.bz2"
Hi,
I have updated the https URL

2025-01-24 08:36 UTC, suresh-thelkar commented
@durgajagadeesh, some PR checks are failing. Please look into it.

2025-02-06 05:10 UTC, suresh-thelkar requested changes
Most of the code changes look good to me. I have couple of minor comments. Can you please look into it.

2025-02-06 05:10 UTC, suresh-thelkar commented on SPECS-EXTENDED/nilfs-utils/nilfs-utils.spec
>  Release:	3%{?dist}
Increment the release number to 4.

2025-02-06 05:10 UTC, suresh-thelkar commented on SPECS-EXTENDED/nilfs-utils/nilfs-utils.spec
> +* Tue Dec 17 2024 Durga Jagadeesh Palli <v-dpalli@microsoft.com> - 2.2.11-3
Here also use the version as 2.2.11-4.

2025-02-06 11:58 UTC, durgajagadeesh commented on SPECS-EXTENDED/nilfs-utils/nilfs-utils.spec
> +* Tue Dec 17 2024 Durga Jagadeesh Palli <v-dpalli@microsoft.com> - 2.2.11-3
Hi @suresh-thelkar ,
I have added the same in latest commit.
Please review once again.
Thanks!

2025-02-06 12:00 UTC, durgajagadeesh commented on SPECS-EXTENDED/nilfs-utils/nilfs-utils.spec
>  Release:	3%{?dist}
Thanks,
i have added the same now.
Please review once again.

2025-02-07 04:20 UTC, suresh-thelkar approved these changes

2025-02-11 05:35 UTC, suresh-thelkar approved these changes

2025-02-11 06:15 UTC, durgajagadeesh commented
Hi @suresh-thelkar ,
The source tall ball results are okay after your manual build run. 
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=733019&view=results
<img width="257" alt="image" src="https://github.com/user-attachments/assets/92ea29a5-7a73-41f4-aa42-b9332e8f1d37" />

And then all PR checks are also okay.
<img width="634" alt="image" src="https://github.com/user-attachments/assets/0f40e16f-7a44-4da7-81d8-29ab61a552f2" />

Thanks you.

2025-02-16 18:25 UTC, LeoMar4 approved these changes

2025-02-16 18:25 UTC, merged