Upgrade: os-prober version to 1.81
microsoft/azurelinux pull request #11494
Opened 2024-12-17 10:34 UTC by jykanase

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [ ] The toolchain has been rebuilt successfully (or no changes were made to it)
- [ ] The toolchain/worker package manifests are up-to-date
- [ ] Any updated packages successfully build (or no packages were changed)
- [ ] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [ ] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [ ] All package sources are available
- [ ] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [ ] LICENSE-MAP files are up-to-date (`./LICENSES-AND-NOTICES/SPECS/data/licenses.json`, `./LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md`, `./LICENSES-AND-NOTICES/SPECS/LICENSE-EXCEPTIONS.PHOTON`)
- [ ] All source files have up-to-date hashes in the `*.signatures.json` files
- [ ] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [ ] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

Upgrade: os-prober version to 1.81

###### Change Log  

- SPECS-EXTENDED/orc/orc.signatures.json
- SPECS-EXTENDED/orc/orc.spec
-  cgmanifest.json

###### Does this affect the toolchain?  

**NO**

###### Associated issues  

- #xxxx

###### Links to CVEs  
- https://nvd.nist.gov/vuln/detail/CVE-YYYY-XXXX

###### Test Methodology

- Pipeline build id: xxxx

2025-02-14 06:23 UTC, mfrw approved these changes
interim approval for blobstore upload

2025-03-17 08:13 UTC, 0xba1a requested changes

2025-03-17 08:13 UTC, 0xba1a commented on cgmanifest.json
> +          "downloadUrl": "https://ftp.us.debian.org/debian/pool/main/o/os-prober/os-prober_1.81.tar.xz"
It looks like the `https` certificate for this URL is expired or not available. Can you please check whether there are any alternative Secure URL available?

2025-03-18 05:00 UTC, jykanase commented on cgmanifest.json
> +          "downloadUrl": "https://ftp.us.debian.org/debian/pool/main/o/os-prober/os-prober_1.81.tar.xz"
Updated with new Source.

2025-04-11 07:36 UTC, 0xba1a approved these changes

2025-04-11 07:36 UTC, merged