Upgrade: perl-Data-UUID version to 1.227
microsoft/azurelinux pull request #11536
Opened 2024-12-19 04:52 UTC by jykanase

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [ ] The toolchain has been rebuilt successfully (or no changes were made to it)
- [ ] The toolchain/worker package manifests are up-to-date
- [ ] Any updated packages successfully build (or no packages were changed)
- [ ] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [ ] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [ ] All package sources are available
- [ ] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [ ] LICENSE-MAP files are up-to-date (`./LICENSES-AND-NOTICES/SPECS/data/licenses.json`, `./LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md`, `./LICENSES-AND-NOTICES/SPECS/LICENSE-EXCEPTIONS.PHOTON`)
- [ ] All source files have up-to-date hashes in the `*.signatures.json` files
- [ ] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [ ] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

 Upgrade: perl-Data-UUID version to 1.227

###### Change Log  

-  SPECS-EXTENDED/perl-Data-UUID/perl-Data-UUID.signatures.json
-  SPECS-EXTENDED/perl-Data-UUID/perl-Data-UUID.spec
-  cgmanifest.json

###### Does this affect the toolchain?  

**NO**

###### Associated issues  

- #xxxx

###### Links to CVEs  
- https://nvd.nist.gov/vuln/detail/CVE-YYYY-XXXX

###### Test Methodology

- Pipeline build id: xxxx

2025-01-08 11:25 UTC, Sumynwa commented
Buddy Build Local pipeline: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=707136&view=results

2025-01-08 11:30 UTC, Sumynwa requested changes

2025-01-08 11:30 UTC, Sumynwa commented on SPECS-EXTENDED/perl-Data-UUID/perl-Data-UUID.signatures.json
> +}
no newline error, please fix

2025-01-08 11:30 UTC, Sumynwa commented on SPECS-EXTENDED/perl-Data-UUID/perl-Data-UUID.spec
> -Requires:	perl(:MODULE_COMPAT_%(eval "`perl -V:version`"; echo $version))
The Runtime dependency on perl(:MODULE_COMPAT_<version>) is required.
This is provided by the **perl-libs** subpackage which provides the **libperl.so.***.

Otherwise, the runtime requirement on libperl.so will be unmet.

This is also the reason for Buddy Build's Install built package job to fail with error "package perl-Data-UUID-1.227-4.azl3.x86_64 requires libperl.so.5.38()(64bit), but none of the providers can be installed".

2025-01-08 14:32 UTC, jykanase commented on SPECS-EXTENDED/perl-Data-UUID/perl-Data-UUID.spec
> -Requires:	perl(:MODULE_COMPAT_%(eval "`perl -V:version`"; echo $version))
I have Updated the changes

2025-02-07 06:36 UTC, Sumynwa approved these changes
LGTM. Thanks.

2025-02-16 18:12 UTC, LeoMar4 approved these changes

2025-02-16 18:12 UTC, merged