ocaml-curses: update to 1.0.11
microsoft/azurelinux pull request #11566
Opened 2024-12-19 20:51 UTC by durgajagadeesh

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./LICENSES-AND-NOTICES/SPECS/data/licenses.json`, `./LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md`, `./LICENSES-AND-NOTICES/SPECS/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [x] Ready to merge

---

###### Summary 

ocaml-curses: update to 1.0.11

###### Build/Dependency Information 
The PR is a leaf PR which builds alone successfully.

###### Change Log  

../SPECS-EXTENDED/ocaml-curses/ocaml-curses.signatures.json
../SPECS-EXTENDED/ocaml-curses/ocaml-curses.spec
../cgmanifest.json
[ocaml-curses-1.0.11-1.azl3.src.rpm.log](https://github.com/user-attachments/files/18203115/ocaml-curses-1.0.11-1.azl3.src.rpm.log)

###### Does this affect the toolchain?  

**NO**

###### Associated issues  

- #xxxx

###### Links to CVEs  
- https://nvd.nist.gov/vuln/detail/CVE-YYYY-XXXX

###### Test Methodology

- Pipeline build id: xxxx

2024-12-19 20:55 UTC, durgajagadeesh commented
This package built successfully, no run time errors.

2025-02-17 04:19 UTC, suresh-thelkar requested changes
Code changes look good to me. I have left a minor comment. Please take a look.

2025-02-17 04:19 UTC, suresh-thelkar commented on SPECS-EXTENDED/ocaml-curses/ocaml-curses.spec
> +Release:        11%{?dist}
Increase the release number to 14.

2025-03-11 10:11 UTC, suresh-thelkar approved these changes

2025-03-12 18:06 UTC, merged