Upgarde: pkcs11-helper to version 1.30.0
microsoft/azurelinux pull request #11565
Opened 2024-12-19 20:06 UTC by SumitJenaHCL

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [ ] The toolchain has been rebuilt successfully (or no changes were made to it)
- [ ] The toolchain/worker package manifests are up-to-date
- [ ] Any updated packages successfully build (or no packages were changed)
- [ ] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [ ] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [ ] All package sources are available
- [ ] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [ ] LICENSE-MAP files are up-to-date (`./LICENSES-AND-NOTICES/SPECS/data/licenses.json`, `./LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md`, `./LICENSES-AND-NOTICES/SPECS/LICENSE-EXCEPTIONS.PHOTON`)
- [ ] All source files have up-to-date hashes in the `*.signatures.json` files
- [ ] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [ ] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

What does the PR accomplish, why was it needed?
This PR is to Upgrade the package pkcs11-helper to version 1.30.0

###### Change Log  

- SPECS-EXTENDED/pkcs11-helper/pkcs11-helper-rfc7512.patch
- SPECS-EXTENDED/pkcs11-helper/pkcs11-helper.signatures.json
- SPECS-EXTENDED/pkcs11-helper/pkcs11-helper.spec
- cgmanifest.json

###### Does this affect the toolchain?  

**NO**

###### Associated issues  

- #xxxx

###### Links to CVEs  
- https://nvd.nist.gov/vuln/detail/CVE-YYYY-XXXX

###### Test Methodology

- Local Build

2025-04-15 01:20 UTC, kgodara912 requested changes
Good for next stage: buddy build pipeline.

2025-04-18 14:14 UTC, SumitJenaHCL commented on SPECS-EXTENDED/pkcs11-helper/pkcs11-helper.spec
> +* Wed Dec 18 2024 Sumit Jena <v-sumitjena@microsoft.com> - 1.30.0-1
Fixed.

2025-07-29 04:37 UTC, sandeepkarambelkar commented
Buddy Build - https://dev.azure.com/mariner-org/mariner/_build/results?buildId=883993&view=results

2025-07-29 06:08 UTC, sandeepkarambelkar commented
RPMs installation tests failed in buddy build. @SumitJenaHCL , can you download the built rpms and verify the installation?

2025-07-29 06:17 UTC, cyberbandya007 commented
The pipeline failure is due to libcrypt.so.3 but based on the libcrypt spec, we ship libcrypt.so.2. Need to verify the installation from the local machine too.

2025-09-02 04:51 UTC, SumitJenaHCL commented
<img width="1218" height="578" alt="image" src="https://github.com/user-attachments/assets/44c6db85-ddf4-4510-b429-f0af1ac974c7" />
Installation successful.

2025-09-03 13:46 UTC, cyberbandya007 approved these changes
Changes LGTM. Installation failures are verified on local using generated RPMs.

2025-09-03 15:03 UTC, LeoMar4 approved these changes

2025-09-04 06:30 UTC, kgodara912 approved these changes

2025-09-04 06:31 UTC, merged