Upgraded mod_intercept_form_submit to version 1.2.0
microsoft/azurelinux pull request #11571
Opened 2024-12-19 22:25 UTC by aninda-al

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./LICENSES-AND-NOTICES/SPECS/data/licenses.json`, `./LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md`, `./LICENSES-AND-NOTICES/SPECS/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

Upgrades mod_intercept_form_submit to version 1.2.0

###### Change Log  

- modified:   SPECS-EXTENDED/mod_intercept_form_submit/mod_intercept_form_submit.signatures.json
- modified:   SPECS-EXTENDED/mod_intercept_form_submit/mod_intercept_form_submit.spec
- modified:   cgmanifest.json

###### Does this affect the toolchain?  

**NO**

###### Associated issues  

- NA

###### Links to CVEs  
- NA

###### Test Methodology

- local build

2025-02-10 05:55 UTC, suresh-thelkar requested changes

2025-02-10 05:55 UTC, suresh-thelkar commented on SPECS-EXTENDED/mod_intercept_form_submit/mod_intercept_form_submit.spec
> +Provides: mod_authnz_pam >= 0.7
Can you please justify the reason for adding these Provides clause.

2025-02-10 16:39 UTC, aninda-al commented on SPECS-EXTENDED/mod_intercept_form_submit/mod_intercept_form_submit.spec
> +Provides: mod_authnz_pam >= 0.7
@suresh-thelkar I believe I made this change from Requires to Provides to get rid of the unresolved dependency. Today, I tried to build by removing both of these lines and it builds fine. I was also able to install the rpm on a AL3.0 docker image without any issue. Is it ok to get rid of these two lines from the spec file? Once you confirm I"ll push my changes. Thanks!

2025-04-09 01:11 UTC, aninda-al commented on SPECS-EXTENDED/mod_intercept_form_submit/mod_intercept_form_submit.spec
> +Provides: mod_authnz_pam >= 0.7
Moved back httpd-mmn under provides but had to remove the version check as the version value was 0-0

2025-08-23 13:01 UTC, aninda-al commented on SPECS-EXTENDED/mod_intercept_form_submit/mod_intercept_form_submit.spec
> +Provides: mod_authnz_pam >= 0.7
@suresh-thelkar Could you please rebuild with its dependency mod_authnz_pam, BB install is failing

2026-05-17 05:04 UTC, closed without merging