Upgrade: pps-tools to version 1.0.3
microsoft/azurelinux pull request #11609
Opened 2024-12-20 18:41 UTC by SumitJenaHCL

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [ ] The toolchain has been rebuilt successfully (or no changes were made to it)
- [ ] The toolchain/worker package manifests are up-to-date
- [ ] Any updated packages successfully build (or no packages were changed)
- [ ] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [ ] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [ ] All package sources are available
- [ ] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [ ] LICENSE-MAP files are up-to-date (`./LICENSES-AND-NOTICES/SPECS/data/licenses.json`, `./LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md`, `./LICENSES-AND-NOTICES/SPECS/LICENSE-EXCEPTIONS.PHOTON`)
- [ ] All source files have up-to-date hashes in the `*.signatures.json` files
- [ ] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [ ] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

What does the PR accomplish, why was it needed?
This PR is to upgrade the package pps-tools to version 1.0.3

###### Change Log  

- SPECS-EXTENDED/pps-tools/pps-tools.signatures.json
- SPECS-EXTENDED/pps-tools/pps-tools.spec
- cgmanifest.json

###### Does this affect the toolchain?  

**NO**

###### Associated issues  

- #xxxx

###### Links to CVEs  
- https://nvd.nist.gov/vuln/detail/CVE-YYYY-XXXX

###### Test Methodology

- Local Build

2025-02-14 10:33 UTC, Sumynwa requested changes

2025-02-14 10:33 UTC, Sumynwa commented on SPECS-EXTENDED/pps-tools/pps-tools.spec
> +* Wed Dec 18 2024 Sumit Jena <v-sumitjena@microsoft.com> - 1.0.3-1
Please fix the release string to be in sequence with the changelog.

2025-02-14 10:33 UTC, Sumynwa commented on SPECS-EXTENDED/pps-tools/pps-tools.spec
> +- Azure Linux import from Fedora 41 (license: MIT).
Please validate this line, something similar to `Initial <> import`

2025-02-14 10:33 UTC, Sumynwa commented on SPECS-EXTENDED/pps-tools/pps-tools.spec
> +Release:	1%{?dist}
Please fix the release string

2025-02-14 10:33 UTC, Sumynwa commented
Buddy Build Run: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=706470&view=results

2025-02-25 13:46 UTC, SumitJenaHCL commented on SPECS-EXTENDED/pps-tools/pps-tools.spec
> +Release:	1%{?dist}
Added Requested changes. requesting for review.

2025-02-25 13:46 UTC, SumitJenaHCL commented on SPECS-EXTENDED/pps-tools/pps-tools.spec
> +* Wed Dec 18 2024 Sumit Jena <v-sumitjena@microsoft.com> - 1.0.3-1
Added Requested changes. requesting for review.

2025-02-25 13:47 UTC, SumitJenaHCL commented on SPECS-EXTENDED/pps-tools/pps-tools.spec
> +- Azure Linux import from Fedora 41 (license: MIT).
Added Requested changes. requesting for review.

2025-02-28 08:13 UTC, Sumynwa requested changes

2025-02-28 08:13 UTC, Sumynwa commented on SPECS-EXTENDED/pps-tools/pps-tools.signatures.json
> +}
Fix no new line error

2025-02-28 08:57 UTC, SumitJenaHCL commented on SPECS-EXTENDED/pps-tools/pps-tools.signatures.json
> +}
Added Requested changes. requesting for review.

2025-03-10 08:26 UTC, Sumynwa approved these changes

2025-03-12 18:11 UTC, LeoMar4 approved these changes

2025-03-12 18:11 UTC, merged