Upgraded mythes to version 1.2.5
microsoft/azurelinux pull request #11600
Opened 2024-12-20 14:25 UTC by aninda-al

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./LICENSES-AND-NOTICES/SPECS/data/licenses.json`, `./LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md`, `./LICENSES-AND-NOTICES/SPECS/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

Upgrades mythes to version 1.2.5

###### Change Log  

- modified:   SPECS-EXTENDED/mythes/mythes.signatures.json
- modified:   SPECS-EXTENDED/mythes/mythes.spec
- modified:   cgmanifest.json

###### Does this affect the toolchain?  

**NO**

###### Associated issues  

- NA

###### Links to CVEs  
- NA

###### Test Methodology

- local build

2025-04-11 08:42 UTC, Sumynwa requested changes

2025-04-11 08:42 UTC, Sumynwa commented on SPECS-EXTENDED/mythes/mythes.spec
> +* Mon Dec 30 2024 Aninda Pradhan <v-anipradhan@microsoft.com> - 1.2.5-8
Fix the release string to `7`.

2025-04-11 08:42 UTC, Sumynwa commented on SPECS-EXTENDED/mythes/mythes.spec
> +Release:   8%{?dist}
Fix release string to `7`

2025-04-11 08:42 UTC, Sumynwa commented
BB run: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=776531&view=results

2025-06-26 08:03 UTC, Sumynwa approved these changes

2025-08-16 22:36 UTC, aninda-al commented on SPECS-EXTENDED/mythes/mythes.spec
> +Release:   8%{?dist}
Fixed release number

2025-09-18 11:51 UTC, sandeepkarambelkar commented
Buddy Build - https://dev.azure.com/mariner-org/mariner/_build/results?buildId=931171&view=results

2025-09-19 09:34 UTC, sallhms commented
> Buddy Build - https://dev.azure.com/mariner-org/mariner/_build/results?buildId=931171&view=results

License check issue in build

WARN[0004][licensecheck] Found 1 packages with non-fatal license issues 
INFO[0004][licensecheck] Writing results to file (/mnt/vss/_work/1/s/out/license_check/license_check_results_pkg.json) 
INFO[0004][licensecheck] Writing summary to file (/mnt/vss/_work/1/s/build/license_check_tool/license_check_summary.txt) 
WARN[0004][licensecheck] License check completed with warnings        
make: Leaving directory '/mnt/vss/_work/1/s/CBL-Mariner/toolkit'
##[warning]License issues found.
WARN: (mythes-1.2.5-7.azl3.x86_64.rpm) has license warnings:
	bad %doc files:
		/usr/share/doc/mythes/COPYING

2025-09-19 18:11 UTC, aninda-al commented
> > Buddy Build - https://dev.azure.com/mariner-org/mariner/_build/results?buildId=931171&view=results
> 
> License check issue in build
> 
> WARN[0004][licensecheck] Found 1 packages with non-fatal license issues INFO[0004][licensecheck] Writing results to file (/mnt/vss/_work/1/s/out/license_check/license_check_results_pkg.json) INFO[0004][licensecheck] Writing summary to file (/mnt/vss/_work/1/s/build/license_check_tool/license_check_summary.txt) WARN[0004][licensecheck] License check completed with warnings make: Leaving directory '/mnt/vss/_work/1/s/CBL-Mariner/toolkit' ##[warning]License issues found. WARN: (mythes-1.2.5-7.azl3.x86_64.rpm) has license warnings: bad %doc files: /usr/share/doc/mythes/COPYING

@cyberbandya007 @sallhms  Added a fix for the license check issue. Could you please retrigger another build for this PR?

2025-09-24 11:20 UTC, sandeepkarambelkar commented
Buddy Build - https://dev.azure.com/mariner-org/mariner/_build/results?buildId=936775&view=results

2025-09-25 10:37 UTC, aninda-al commented
> Buddy Build - https://dev.azure.com/mariner-org/mariner/_build/results?buildId=936775&view=results

@cyberbandya007 The buddybuild result of this package is all green. Could you please approve it? Thanks! 
<img width="767" height="986" alt="image" src="https://github.com/user-attachments/assets/23abbbb2-f953-4109-8102-dd5b7af11b27" />

2025-09-30 07:46 UTC, cyberbandya007 commented on SPECS-EXTENDED/mythes/mythes.spec
> +* Wed Feb 23 2023 Caolán McNamara <caolanm@redhat.com> - 1.2.5-3
Correct the day for changelog. Thu Feb 23 2023

2025-09-30 09:53 UTC, kgodara912 approved these changes
Buddy build is successful for the package. Minor version upgrade and proper marking of license files, LGTM.

2025-10-01 04:07 UTC, merged