Upgrade: pyparted to version 3.58
microsoft/azurelinux pull request #11613
Opened 2024-12-20 18:48 UTC by SumitJenaHCL

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [ ] The toolchain has been rebuilt successfully (or no changes were made to it)
- [ ] The toolchain/worker package manifests are up-to-date
- [ ] Any updated packages successfully build (or no packages were changed)
- [ ] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [ ] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [ ] All package sources are available
- [ ] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [ ] LICENSE-MAP files are up-to-date (`./LICENSES-AND-NOTICES/SPECS/data/licenses.json`, `./LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md`, `./LICENSES-AND-NOTICES/SPECS/LICENSE-EXCEPTIONS.PHOTON`)
- [ ] All source files have up-to-date hashes in the `*.signatures.json` files
- [ ] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [ ] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

What does the PR accomplish, why was it needed?
This PR is to upgrade the package pyparted to version 3.58

###### Change Log  

- SPECS-EXTENDED/pyparted/keyring.gpg
- SPECS-EXTENDED/pyparted/pyparted-3.13.0.tar.gz.asc
- SPECS-EXTENDED/pyparted/pyparted.signatures.json
- SPECS-EXTENDED/pyparted/pyparted.spec
- SPECS-EXTENDED/pyparted/trustdb.gpg
- cgmanifest.json

###### Does this affect the toolchain?  

**NO**

###### Associated issues  

- #xxxx

###### Links to CVEs  
- https://nvd.nist.gov/vuln/detail/CVE-YYYY-XXXX

###### Test Methodology

- Local Build

2025-02-14 10:45 UTC, Sumynwa requested changes

2025-02-14 10:45 UTC, Sumynwa commented on SPECS-EXTENDED/pyparted/pyparted.spec
> +* Wed Dec 18 2024 Sumit Jena <v-sumitjena@microsoft.com> - 3.13.0-1
Fix the release number to be in sequece with changelog

2025-02-14 10:45 UTC, Sumynwa commented on SPECS-EXTENDED/pyparted/pyparted.spec
> +- Azure Linux import from Fedora 41 (license: MIT).
Please check the import line

2025-02-14 10:45 UTC, Sumynwa commented on SPECS-EXTENDED/pyparted/pyparted.spec
> +Release:       1%{?dist}
Please fix release string

2025-02-14 10:45 UTC, Sumynwa commented
Buddy Build Run: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=717670&view=results

2025-02-17 12:57 UTC, SumitJenaHCL commented on SPECS-EXTENDED/pyparted/pyparted.spec
> +* Wed Dec 18 2024 Sumit Jena <v-sumitjena@microsoft.com> - 3.13.0-1
Added requested changes. Requesting for review.

2025-02-17 12:57 UTC, SumitJenaHCL commented on SPECS-EXTENDED/pyparted/pyparted.spec
> +* Wed Dec 18 2024 Sumit Jena <v-sumitjena@microsoft.com> - 3.13.0-1
Added requested changes. Requesting for review.

2025-02-17 12:57 UTC, SumitJenaHCL commented on SPECS-EXTENDED/pyparted/pyparted.spec
> +* Wed Dec 18 2024 Sumit Jena <v-sumitjena@microsoft.com> - 3.13.0-1
Added requested changes. Requesting for review.

2025-02-17 12:57 UTC, SumitJenaHCL commented on SPECS-EXTENDED/pyparted/pyparted.spec
> +* Wed Dec 18 2024 Sumit Jena <v-sumitjena@microsoft.com> - 3.13.0-1
Added requested changes. Requesting for review.

2025-02-17 12:57 UTC, SumitJenaHCL commented on SPECS-EXTENDED/pyparted/pyparted.spec
> +- Azure Linux import from Fedora 41 (license: MIT).
Added requested changes. Requesting for review.

2025-02-28 08:20 UTC, Sumynwa commented
Buddy Build Run: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=738384&view=results

2025-03-10 08:24 UTC, Sumynwa commented on SPECS-EXTENDED/pyparted/pyparted.signatures.json
> +}
Please fix no new line error

2025-03-10 08:25 UTC, Sumynwa commented on SPECS-EXTENDED/pyparted/pyparted.spec
> +Epoch:         1
Please drop epoch

2025-04-11 06:42 UTC, Sumynwa approved these changes

2025-04-24 17:27 UTC, LeoMar4 approved these changes

2025-04-24 17:27 UTC, merged