Updating CBL-Mariner import Fedora 41 (Version 0.16 -> 0.17).
microsoft/azurelinux pull request #11634
Opened 2024-12-21 04:16 UTC by v-smalavathu

- Added "License verified" statement to the changelog.

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [x] The toolchain has been rebuilt successfully (or no changes were made to it)
- [x] The toolchain/worker package manifests are up-to-date
- [x] Any updated packages successfully build (or no packages were changed)
- [x] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./LICENSES-AND-NOTICES/SPECS/data/licenses.json`, `./LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md`, `./LICENSES-AND-NOTICES/SPECS/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [x] Ready to merge

---

###### Summary 

Updating CBL-Mariner import Fedora 41 (Version 0.16 -> 0.17).
- Added "License verified" statement to the changelog.

###### Change Log  

- Updating CBL-Mariner import Fedora 41 (Version 0.16 -> 0.17).
- Added "License verified" statement to the changelog.

###### Does this affect the toolchain?  

NO

###### Associated issues  

- #xxxx

###### Links to CVEs  
- https://nvd.nist.gov/vuln/detail/CVE-YYYY-XXXX

###### Test Methodology

- Pipeline build id: xxxx

2025-01-07 10:37 UTC, Sumynwa commented
Buddy Build local pipeline run: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=706089&view=results

2025-01-07 10:42 UTC, Sumynwa requested changes

2025-01-07 10:42 UTC, Sumynwa commented on SPECS-EXTENDED/perl-Test-Synopsis/perl-Test-Synopsis.signatures.json
> +  "Test-Synopsis-0.17.tar.gz": "d268c98b33d2fa14dbb22b20d6561bab489ee82587dfbe19ad277620c7b8b6de"
Please keep the naming similar to perl-Test-Synopsis with the version string changed.

2025-01-07 10:42 UTC, Sumynwa commented on SPECS-EXTENDED/perl-Test-Synopsis/perl-Test-Synopsis.spec
> +Source0:	https://cpan.metacpan.org/authors/id/Z/ZO/ZOFFIX/Test-Synopsis-%{version}.tar.gz
keep the original `#/perl-Test-Synopsis-%{version}.tar.gz` string appended to source0 string for source name clarity

2025-01-07 17:31 UTC, v-smalavathu commented on SPECS-EXTENDED/perl-Test-Synopsis/perl-Test-Synopsis.signatures.json
> +  "Test-Synopsis-0.17.tar.gz": "d268c98b33d2fa14dbb22b20d6561bab489ee82587dfbe19ad277620c7b8b6de"
The available source name is not in my hand, It's available at provided website and I can't change it.

2025-01-07 17:32 UTC, v-smalavathu commented on SPECS-EXTENDED/perl-Test-Synopsis/perl-Test-Synopsis.spec
> +Source0:	https://cpan.metacpan.org/authors/id/Z/ZO/ZOFFIX/Test-Synopsis-%{version}.tar.gz
The available source name is not in my hand, It's available at provided website and I can't change it.

2025-01-08 11:49 UTC, Sumynwa requested changes

2025-01-08 11:49 UTC, Sumynwa commented on SPECS-EXTENDED/perl-Test-Synopsis/perl-Test-Synopsis.spec
> -Requires:	perl(:MODULE_COMPAT_%(eval "`perl -V:version`"; echo $version))
We need to keep the runtime requirement on perl-libs. We must not delete this.

2025-01-08 18:16 UTC, v-smalavathu commented on SPECS-EXTENDED/perl-Test-Synopsis/perl-Test-Synopsis.spec
> -Requires:	perl(:MODULE_COMPAT_%(eval "`perl -V:version`"; echo $version))
Now, I got it.
-Thanks

2025-01-08 19:01 UTC, v-smalavathu commented on SPECS-EXTENDED/perl-Test-Synopsis/perl-Test-Synopsis.spec
> -Requires:	perl(:MODULE_COMPAT_%(eval "`perl -V:version`"; echo $version))
Updated.

2025-02-07 11:09 UTC, Sumynwa requested changes

2025-02-12 05:31 UTC, Sumynwa approved these changes
LGTM. Thanks.

2025-02-16 18:05 UTC, LeoMar4 approved these changes

2025-02-16 18:05 UTC, merged