Upgrade: python-pymongo version to 4.2.0
microsoft/azurelinux pull request #11637
Opened 2024-12-21 11:11 UTC by akhila-guruju

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [ ] The toolchain has been rebuilt successfully (or no changes were made to it)
- [ ] The toolchain/worker package manifests are up-to-date
- [ ] Any updated packages successfully build (or no packages were changed)
- [ ] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [ ] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [ ] All package sources are available
- [ ] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [ ] LICENSE-MAP files are up-to-date (`./LICENSES-AND-NOTICES/SPECS/data/licenses.json`, `./LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md`, `./LICENSES-AND-NOTICES/SPECS/LICENSE-EXCEPTIONS.PHOTON`)
- [ ] All source files have up-to-date hashes in the `*.signatures.json` files
- [ ] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [ ] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

Upgrade: python-pymongo version to 4.2.0

###### Change Log  

- deleted:    SPECS-EXTENDED/python-pymongo/SOURCES/0001-Use-ssl.match_hostname-from-the-Python-stdlib.patch
- modified:   SPECS-EXTENDED/python-pymongo/python-pymongo.signatures.json
- modified:   SPECS-EXTENDED/python-pymongo/python-pymongo.spec
- modified:   cgmanifest.json

###### Does this affect the toolchain?  

**NO**

###### Associated issues  

- #xxxx

###### Links to CVEs  
- https://nvd.nist.gov/vuln/detail/CVE-YYYY-XXXX

###### Test Methodology

- Pipeline build id: xxxx

2025-01-06 12:51 UTC, 0xba1a commented
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=704821&view=results

2025-01-07 06:51 UTC, akhila-guruju commented
Modified Source URL same as the URL in cgmanifest.json file.

2025-02-10 04:39 UTC, suresh-thelkar requested changes

2025-02-10 04:39 UTC, suresh-thelkar commented on SPECS-EXTENDED/python-pymongo/python-pymongo.spec
>  %setup -q -n mongo-python-driver-%{version}
use autosetup macro instead.

2025-02-11 04:25 UTC, akhila-guruju commented on SPECS-EXTENDED/python-pymongo/python-pymongo.spec
>  %setup -q -n mongo-python-driver-%{version}
Updated with autosetup macro

2025-04-16 04:36 UTC, suresh-thelkar approved these changes

2025-04-24 17:33 UTC, LeoMar4 approved these changes

2025-04-24 17:33 UTC, merged