Upgrade: python-varlink version to 31.0.0
microsoft/azurelinux pull request #11677
Opened 2024-12-23 12:15 UTC by akhila-guruju

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [ ] The toolchain has been rebuilt successfully (or no changes were made to it)
- [ ] The toolchain/worker package manifests are up-to-date
- [ ] Any updated packages successfully build (or no packages were changed)
- [ ] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [ ] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [ ] All package sources are available
- [ ] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [ ] LICENSE-MAP files are up-to-date (`./LICENSES-AND-NOTICES/SPECS/data/licenses.json`, `./LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md`, `./LICENSES-AND-NOTICES/SPECS/LICENSE-EXCEPTIONS.PHOTON`)
- [ ] All source files have up-to-date hashes in the `*.signatures.json` files
- [ ] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [ ] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

Upgrade: python-varlink version to 31.0.0

###### Change Log  

- modified:   SPECS-EXTENDED/python-varlink/python-varlink.signatures.json
- modified:   SPECS-EXTENDED/python-varlink/python-varlink.spec
- modified:   cgmanifest.json

###### Does this affect the toolchain?  

**NO**

###### Associated issues  

- #xxxx

###### Links to CVEs  
- https://nvd.nist.gov/vuln/detail/CVE-YYYY-XXXX

###### Test Methodology

- Pipeline build id: xxxx

2024-12-30 05:03 UTC, suresh-thelkar requested changes

2024-12-30 05:03 UTC, suresh-thelkar commented on SPECS-EXTENDED/python-varlink/python-varlink.signatures.json
> +  "python-varlink-31.0.0.tar.gz": "3c1f0ef71d887717e890a195811569535991863fa21da0c23c176d58f1732ebe"
It looks like the checksum is wrong. Can you please double check.

2025-03-13 09:13 UTC, akhila-guruju commented on SPECS-EXTENDED/python-varlink/python-varlink.signatures.json
> +  "python-varlink-31.0.0.tar.gz": "3c1f0ef71d887717e890a195811569535991863fa21da0c23c176d58f1732ebe"
Checked it. It is same. The one used for building and those which are mentioned in cgmanifest & source0, all are having same shasum.
![Screenshot 2024-12-30 152201](https://github.com/user-attachments/assets/0eb3d4da-e69c-493d-845e-92ec705c3d59)

2025-03-21 04:44 UTC, akhila-guruju commented on SPECS-EXTENDED/python-varlink/python-varlink.signatures.json
> +  "python-varlink-31.0.0.tar.gz": "3c1f0ef71d887717e890a195811569535991863fa21da0c23c176d58f1732ebe"
Verified. It is same.

2025-04-17 05:32 UTC, akhila-guruju commented on SPECS-EXTENDED/python-varlink/python-varlink.signatures.json
> +  "python-varlink-31.0.0.tar.gz": "3c1f0ef71d887717e890a195811569535991863fa21da0c23c176d58f1732ebe"
Done.

2025-05-29 04:03 UTC, suresh-thelkar reviewed
One of the GitHub Checks is failing, Can you please take a look.

2025-05-29 04:14 UTC, suresh-thelkar approved these changes
Code changes look good to me. Please upload the buddy build results when it runs.

2025-05-29 04:53 UTC, akhila-guruju commented
BB result - [Buddy Build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=788748&view=results)

2026-05-17 05:04 UTC, closed without merging