Upgrade: python-blivet to version 3.11.0
microsoft/azurelinux pull request #11670
Opened 2024-12-23 09:10 UTC by SumitJenaHCL

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [ ] The toolchain has been rebuilt successfully (or no changes were made to it)
- [ ] The toolchain/worker package manifests are up-to-date
- [ ] Any updated packages successfully build (or no packages were changed)
- [ ] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [ ] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [ ] All package sources are available
- [ ] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [ ] LICENSE-MAP files are up-to-date (`./LICENSES-AND-NOTICES/SPECS/data/licenses.json`, `./LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md`, `./LICENSES-AND-NOTICES/SPECS/LICENSE-EXCEPTIONS.PHOTON`)
- [ ] All source files have up-to-date hashes in the `*.signatures.json` files
- [ ] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [ ] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

What does the PR accomplish, why was it needed?
This PR is to upgrade the package python-blivet to version 3.11.0

###### Change Log  

- SPECS-EXTENDED/python-blivet/0002-Do-not-raise-libblockdev-errors-in-FSMinSize-tasks.patch
- SPECS-EXTENDED/python-blivet/0003-free_space_estimate-adjust-for-compression-on-btrfs.patch
- SPECS-EXTENDED/python-blivet/python-blivet.signatures.json
- SPECS-EXTENDED/python-blivet/python-blivet.spec
- cgmanifest.json

###### Does this affect the toolchain?  

**NO**

###### Associated issues  

- #xxxx

###### Links to CVEs  
- https://nvd.nist.gov/vuln/detail/CVE-YYYY-XXXX

###### Test Methodology

- Local Build. (needs to update the package util-linux from core to provide aditional runtime dependencies)

2025-04-15 01:06 UTC, kgodara912 requested changes

2025-04-18 14:10 UTC, SumitJenaHCL commented on SPECS-EXTENDED/python-blivet/python-blivet.signatures.json
> +  "blivet-3.11.0.tar.gz": "c56e10454537542681731146f4ab55b3a0c35b51ddd61fd0b4859b95d64ff152"
The project URL still seems to be active and is also used in latest fedora development. And the repository is the one used in python module index.

2025-04-18 14:10 UTC, SumitJenaHCL commented on cgmanifest.json
> +          "downloadUrl": "http://github.com/storaged-project/blivet/archive/blivet-3.11.0.tar.gz"
The project URL still seems to be active and is also used in latest fedora development. And the repository is the one used in python module index.

2025-04-18 14:12 UTC, SumitJenaHCL commented on cgmanifest.json
> +          "downloadUrl": "http://github.com/storaged-project/blivet/archive/blivet-3.11.0.tar.gz"
The test files still seems to be active.

2026-05-17 05:04 UTC, closed without merging