Upgrade: perl-Crypt-OpenSSL-RSA to version 0.33
microsoft/azurelinux pull request #11688
Opened 2024-12-23 18:57 UTC by SumitJenaHCL

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [ ] The toolchain has been rebuilt successfully (or no changes were made to it)
- [ ] The toolchain/worker package manifests are up-to-date
- [ ] Any updated packages successfully build (or no packages were changed)
- [ ] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [ ] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [ ] All package sources are available
- [ ] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [ ] LICENSE-MAP files are up-to-date (`./LICENSES-AND-NOTICES/SPECS/data/licenses.json`, `./LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md`, `./LICENSES-AND-NOTICES/SPECS/LICENSE-EXCEPTIONS.PHOTON`)
- [ ] All source files have up-to-date hashes in the `*.signatures.json` files
- [ ] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [ ] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

What does the PR accomplish, why was it needed?
This PR is to upgrade the package perl-Crypt-OpenSSL-RSA to version 0.33

###### Change Log  

- SPECS-EXTENDED/perl-Crypt-OpenSSL-RSA/perl-Crypt-OpenSSL-RSA.signatures.json
- SPECS-EXTENDED/perl-Crypt-OpenSSL-RSA/perl-Crypt-OpenSSL-RSA.spec
- cgmanifest.json

###### Does this affect the toolchain?  

**NO**

###### Associated issues  

- #xxxx

###### Links to CVEs  
- https://nvd.nist.gov/vuln/detail/CVE-YYYY-XXXX

###### Test Methodology

- Local Build. (Needs to be build along with perl-Crypt-OpenSSL-Bignum, perl-Crypt-OpenSSL-Guess, perl-Crypt-OpenSSL-Random)

2025-03-03 10:27 UTC, suresh-thelkar requested changes
Code changes look good to me. Install/uninstall tests from the [buddy build](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=743835&view=results) are failing. Can you please take a look. 
If you have already verified them in a Azure Linux 3.0 container, please share the screenshot for the same.

2025-03-11 17:30 UTC, SumitJenaHCL commented
Uploaded Screenshot verifying the installation/uninstallation of the package.

2025-07-29 04:16 UTC, cyberbandya007 requested changes

2025-07-29 04:16 UTC, cyberbandya007 commented on SPECS-EXTENDED/perl-Crypt-OpenSSL-RSA/perl-Crypt-OpenSSL-RSA.spec
>  %install
Can you add check section with some tests?

2025-07-29 04:17 UTC, cyberbandya007 commented
Buddy Build - https://dev.azure.com/mariner-org/mariner/_build/results?buildId=883954&view=results

2025-07-29 04:19 UTC, SumitJenaHCL commented on SPECS-EXTENDED/perl-Crypt-OpenSSL-RSA/perl-Crypt-OpenSSL-RSA.spec
>  %install
The %check section is already present.

2025-07-29 04:33 UTC, cyberbandya007 commented on SPECS-EXTENDED/perl-Crypt-OpenSSL-RSA/perl-Crypt-OpenSSL-RSA.spec
>  %install
My bad, didn't expand this.

2025-07-29 05:52 UTC, cyberbandya007 commented
Buddy Build have installation failures. @SumitJenaHCL , Can you check the installation of builts RPMs on local and update here.
Started new buddy build with required package during installation - https://dev.azure.com/mariner-org/mariner/_build/results?buildId=884120&view=results

2025-07-29 05:54 UTC, SumitJenaHCL commented
> Buddy Build have installation failures. @SumitJenaHCL , Can you check the installation of builts RPMs on local and update here. Started new buddy build with required package during installation - https://dev.azure.com/mariner-org/mariner/_build/results?buildId=884120&view=results

Installation test screenshot is attached above in the PR summary.

2025-07-29 06:19 UTC, sandeepkarambelkar commented
> > Buddy Build have installation failures. @SumitJenaHCL , Can you check the installation of builts RPMs on local and update here. Started new buddy build with required package during installation - https://dev.azure.com/mariner-org/mariner/_build/results?buildId=884120&view=results
> 
> Installation test screenshot is attached above in the PR summary.

That is from local build. I have specifically mentioned to download the built RPMs on local.

2025-09-02 06:25 UTC, SumitJenaHCL commented
<img width="1216" height="785" alt="image" src="https://github.com/user-attachments/assets/0d83b17d-99d1-48d6-a519-05d4c70cb95c" />
Installation Successful.

2025-09-04 03:57 UTC, suresh-thelkar approved these changes

2025-09-08 04:44 UTC, LeoMar4 approved these changes

2025-09-08 04:44 UTC, merged