kernel: nopatch CVE-2023-46862
microsoft/azurelinux pull request #6703
Opened 2023-11-08 22:47 UTC by neha170

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [X] The toolchain has been rebuilt successfully (or no changes were made to it)
- [X] The toolchain/worker package manifests are up-to-date
- [X] Any updated packages successfully build (or no packages were changed)
- [X] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [X] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [X] All package sources are available
- [X] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [X] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [X] All source files have up-to-date hashes in the `*.signatures.json` files
- [X] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [X] Documentation has been updated to match any changes to the build system
- [X] Ready to merge

---

###### Summary 

kernel: nopatch CVE-2023-46862

###### Change Log  

- kernel: nopatch CVE-2023-46862

###### Does this affect the toolchain?  

**NO**

###### Links to CVEs  
- https://nvd.nist.gov/vuln/detail/CVE-2023-46862

###### Test Methodology

- nopatch

2023-11-08 23:06 UTC, rlmenge requested changes

2023-11-08 23:06 UTC, rlmenge commented on SPECS/kernel/CVE-2023-46862.nopatch
> +But io_uring/fdinfo.c isn't introduced until a4ad4f748ea96202451f88b6385d7283d0f2e513; not backported to 5.15.*
Judging by this [commit](https://github.com/torvalds/linux/commit/a4ad4f748ea96202451f88b6385d7283d0f2e513), the function was moved to a new file. However, we still have the vulnerable function `io_uring_show_fdinfo` in our [code](https://github.com/microsoft/CBL-Mariner-Linux-Kernel/blob/rolling-lts/mariner-2/5.15.137.1/io_uring/io_uring.c#L10414).

2023-11-08 23:51 UTC, neha170 commented on SPECS/kernel/CVE-2023-46862.nopatch
> +But io_uring/fdinfo.c isn't introduced until a4ad4f748ea96202451f88b6385d7283d0f2e513; not backported to 5.15.*
Thanks for pointing this out. Shall we wait for LSG to backport the commit, or do we want to do that ourselves?

2023-11-09 22:06 UTC, rlmenge commented on SPECS/kernel/CVE-2023-46862.nopatch
> +But io_uring/fdinfo.c isn't introduced until a4ad4f748ea96202451f88b6385d7283d0f2e513; not backported to 5.15.*
Because it is Med let's wait for the backport in LTS

2024-09-10 19:50 UTC, closed without merging