Remove systemd-bootstrap dependency in libvirt
microsoft/azurelinux pull request #8699
Opened 2024-04-04 02:34 UTC by BettyRain

###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [X] The toolchain has been rebuilt successfully (or no changes were made to it)
- [X] The toolchain/worker package manifests are up-to-date
- [X] Any updated packages successfully build (or no packages were changed)
- [X] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [X] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [X] All package sources are available
- [X] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [X] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [X] All source files have up-to-date hashes in the `*.signatures.json` files
- [X] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [X] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

What does the PR accomplish, why was it needed?
Remove systemd-bootstrap dependency in libvirt

###### Change Log  

libguesfs wasn't building because of the error:
"package systemd-255-9.azl3.x86_64 obsoletes systemd-bootstrap <= 255-9.azl3 provided by systemd-bootstrap-250.3-17.azl3.x86_64"
To fix the error we decided to remove the systemd-bootstrap dependency from libvirt-daemon-common.

###### Does this affect the toolchain?  

**NO**

###### Test Methodology

- Local build
- Pipeline build id: [543524](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=543524&view=results)

2024-04-04 09:48 UTC, BettyRain commented
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=543589&view=results
libguestfs built!

2024-04-04 18:37 UTC, dmcilvaney requested changes

2024-04-04 19:45 UTC, dmcilvaney commented on SPECS/libvirt/libvirt.spec
> +- Remove systemd-bootstrap dependency
```suggestion
- Make systemd dependency explicit to avoid confusion with systemd-bootstrap.
```

2024-04-04 19:48 UTC, BettyRain commented
New full build:
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=544341&view=results
New buddy build:
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=544340&view=result

2024-04-04 19:55 UTC, anphel31 approved these changes

2024-04-05 06:52 UTC, dmcilvaney approved these changes

2024-04-05 06:54 UTC, merged